import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.scss";
import Script from "next/script";
import AppClientProvider, { BootstrapClient } from "./provider";

const inter = Roboto({
	weight: "400",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<AppClientProvider>
				<body className={inter.className} suppressHydrationWarning={true}>
					{children}
					<BootstrapClient />
				</body>
			</AppClientProvider>
		</html>
	);
}
